### ISSUE TITLE
libreoffice calc support?

### ISSUE THREAD

**Issue by test2a** [dabochen/spreadsheet-is-all-you-need#1]
can you export the file in libreoffice calc file?

it would be good to know if libreoffice can support such large files

**Comment by dabochen** [comment]
based on my test with excel, there might be issues to be fixed after direct export from .numbers file. it's mainly due to the difference in what formulas they support. so I would guess libreoffice might have similar issues which requires manual adjustments.

**Comment by realamirhe** [comment]
As a suggestion couldn't different formats get committed and updated in various branches, NanoGPT.numbers is 8.4MB, and it can be saved via `git clone --single-branch --branch <e.g. numbers-branch> --depth 1` or via tools like `degit`

**Comment by dabochen** [comment]
that's actually a good suggestion, I'm not quite sure how this repo is going to evolve, but if it does includes more version that might benefit from multiple branches, I would certainly consider this!
