### ISSUE TITLE
Can not see the pic

### ISSUE THREAD

**Issue by majiayu000** [dabochen/spreadsheet-is-all-you-need#3]

**Comment by majiayu000** [comment]
![image](https://github.com/dabochen/spreadsheet-is-all-you-need/assets/19658300/75759e96-4af8-4691-bacb-8b14bb0321be)

It is not clear enough to understand....

**Comment by dabochen** [comment]
yeah sorry the image was a bit blurry, the whole thing is just too big. it is better to use the .numbers file, so that you can zoom in and out to see the details. other wise I will be exploring excel to see if this can be exported to it.

**Comment by majiayu000** [comment]
Thanks for your tip. It's first time that I use the mac numbers application. It worked.
