### ISSUE TITLE
License this repository

### ISSUE THREAD

**Issue by ShamrockLee** [dabochen/spreadsheet-is-all-you-need#5]
Thank you for this marvelous demonstration of nanoGPT on spreadsheets!

The Contributing section of the `README.md` states, "Anyone is welcome if they want to build something more complicated than nanoGPT." However, there needs to be explicit instruction on what people can/cannot do with this project and what others could do with their contributions, or everything would fall back to the "all rights reserved" default of copyright laws.

The simplest way to address this issue is to license this repository, i.e., add a `LICENSE` file to its source tree. Many Free and Open Source (FOSS) Licenses are available off the shelf; GitHub people created [choosealicense.com](https://choosealicense.com/) to help project owners choose a license that suits their goals. The original [nanoGPT](https://github.com/karpathy/nanoGPT) project [chooses](https://github.com/karpathy/nanoGPT/blob/master/LICENSE) the *MIT License*, which is a permissive license that poses no limitation other than attribution (mentioning the name of you and project contributors when reproducing/redistributing this project).

(Re-) Licensing a repository requires the agreement of all contributors to the current codebase, which means that both @dabochen and @dodgymike need to agree with the license changes.

Here is the GitHub documentation about repository licensing:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by dabochen** [comment]
Well thank you! I just added the license file
